name: "test"

on:  
  push:
    branches: ['*']
    paths-ignore:
      - 'data/locales/translations/src/*.json'
      - '.github/**/*.*'

jobs:
  # This workflow contains a single job called "build"
  printInputs:
    runs-on: ubuntu-latest
   
    steps:    
      - name: curl
        run: |
          echo "curl start"
          curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -u ${{ secrets.API_TOKEN }} \
            https://api.github.com/repos/igryg/igrig/actions/workflows/7940621/dispatches \
            -d '{"ref":"master"}'
          echo "curl end"
